---
- name: play
  hosts: node1.example.com
  tasks:
  - name: folder creation
    command: " sh /usr/bin/foldercreation.sh "
    register: output
    notify:
    - printmsg
    failed_when: " 'failed' in output.stdoutput "
  - debug:  
     msg: " folder present "
  handlers:
  - name: printmsg
    debug:  
     var: output

      
