---
- name: play
  hosts: localhost
  vars_files: 
  - mypackage
  tasks:
  - name: install package
    apt:
     name: "{{ package }}"
     state: latest
    register: output
  - debug:
     var: output   