---
- name: play
  hosts: dbserver  
  vars_files:
  - myusers
  tasks:
  - name: loop
    user:
     name: "{{ item.username }}" 
     uid: "{{ item.userid }}"
     comment: "{{ item.comment }}" 
     shell: "{{ item.shell }}" 
     state: present 
    loop: "{{ users }}"
    register: useroutput  
  - name: debug
    debug:
     var: useroutput
